#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer SourceBytes {
  uint srcWords[];
};

layout(std430, binding = 1) writeonly buffer DestinationBytes {
  uint dstWords[];
};

layout(push_constant) uniform CopyParams {
  uint wordCount;
  uint byteCount;
} copyParams;

void main() {
  const uint wordIndex = gl_GlobalInvocationID.x;
  if (wordIndex >= copyParams.wordCount) {
    return;
  }
  dstWords[wordIndex] = srcWords[wordIndex];
}
